* What to do?

We want to simulat data for source attribution and therefore need to
write a tool for someone else to do this. This tool need to simulate
sequence data from 6 alleles with the parameters in the the exsisting
file (calculations.R). 3 Populations (think cattle, sheep and
chickens), a migration matrix to indicate the amount of mixing between
the 'animal' population, Sampling fraction for each animal population
to simulate 'human' cases and the desired number of observations in
the final dataset.


* We want to write a paper

* DONE write code to run Hald model in R
* TODO fix the Hald model code
  The code is broken, no matter the input it returns *exactly* equal attribution
  between all food source populations. For some reason the output also
  has fewer dimensions than the input; e.g. if the input data has 30 serovars
  the output only has 26-27. It is expected that it has one less because the
  "others" category is disregarded, but why more are missing is unclear.
* TODO Contact Tine Hald on how to write hald model code
  There is a software called Multibugs @ multibugs.org that seems to
  be a new implementation of OpenBugs that may be convienient.
* TODO Read other paper that have written Hald model in JAGS
  Which paper it this?
* TODO Read original paper by Hald et al.
* TODO write plot function to produce estimates like Mullner fig 2
* TODO Start a paper template in Word
* TODO decide if the mthod we are using for model performance measurement is good enough
